import Foundation

/// A single message in a conversation — user, assistant, or system role.
struct Message: Identifiable, Codable {
    let id: UUID
    let role: Role
    var content: String
    let images: [ImageAttachment]
    let timestamp: Date
    let plan: Plan?
    let artifacts: [Artifact]

    /// The origin of the message.
    enum Role: String, Codable {
        /// Sent by the human user.
        case user
        /// Generated by the LLM / agent.
        case assistant
        /// Internal system note (e.g. plan generation, errors).
        case system
    }

    /// Create a message with an auto-generated id and current timestamp.
    init(
        role: Role,
        content: String,
        images: [ImageAttachment] = [],
        plan: Plan? = nil,
        artifacts: [Artifact] = []
    ) {
        self.id = UUID()
        self.role = role
        self.content = content
        self.images = images
        self.timestamp = Date()
        self.plan = plan
        self.artifacts = artifacts
    }

    /// Create a message with explicit id and timestamp (used when round-tripping from the database).
    init(id: UUID, role: Role, content: String, images: [ImageAttachment], timestamp: Date, plan: Plan?, artifacts: [Artifact]) {
        self.id = id
        self.role = role
        self.content = content
        self.images = images
        self.timestamp = timestamp
        self.plan = plan
        self.artifacts = artifacts
    }
}
